micronaut:
  server:
    port: 8082
  application:
    name: bookinventory
    instance:
      id: ${random.shortuuid}

consul:
  client:
    registration:
      enabled: true
      retryCount: 5
      failFast: false
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

endpoints:
  health:
    enabled: true
    sensitive: false