micronaut:
  application:
    name: bookcatalogue
    instance:
      id: ${random.shortuuid}
  server:
    port: 8081

consul:
  client:
    registration:
      enabled: true
      retryCount: 5
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

endpoints:
  health:
    enabled: true
    sensitive: false